create table if not exists public.authors (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now() not null,
  name text not null,
  phone text,
  books_count integer not null check (books_count > 0),
  display_dates text[] not null default '{}',
  booth_dates text[] not null default '{}'
);

alter table public.authors enable row level security;

drop policy if exists "public can read authors" on public.authors;
drop policy if exists "public can insert authors" on public.authors;
drop policy if exists "public can update authors" on public.authors;
drop policy if exists "public can delete authors" on public.authors;

create policy "public can read authors"
on public.authors for select
using (true);

create policy "public can insert authors"
on public.authors for insert
with check (true);

create policy "public can update authors"
on public.authors for update
using (true)
with check (true);

create policy "public can delete authors"
on public.authors for delete
using (true);
